setx = {"green", "blue"}
sety = {"blue", "yellow"}
print("origanal set elements:")
print(setx)
print(sety)
print("/nIntersection of two said sets:")
setz = setx.intersection(sety)
print(setz)
setz1 = setx.union(sety)
print(setz1)
setz2=setx.diffrence(sety)
print(setz2)
setz3=sety.diffrence(setx)
print(setz3)
setz4=setx.symmetric_diffrence(sety)
print(setz4)
setz5=sety.symmetric_diffrence(setx)
print(setz5)